apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxd
spec:
  selector:
    matchLabels:
      app: nginxd
  template:
    metadata:
      labels:
        app: nginxd
    spec:
      containers:
        - image: czyacr.azurecr.io/webserver:latest
          name: aspnetapp
          ports:
          - containerPort: 8080